name: TBDUtils
version: 2.0
main: computer.austins.tbdutils.TBDUtils
description: Various utilities & enhancements for TBD
authors: ["Austin Albrecht", "Byrt"]
website: https://austins.computer
api-version: '1.20'