on:
  push:
    branches:
      - master
      - production

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2

      - name: Build Plugin Jar
        run: ./gradlew shadowJar

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: TBDUtils
          path: build/libs/

  deploy:
    runs-on: ubuntu-latest
    needs: build

    if: success() && github.ref == 'refs/heads/production'
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - uses: actions/download-artifact@v3
        with:
          name: TBDUtils
          path: deploy

      - name: Setup node
        uses: actions/setup-node@v2
        with:
          node-version: '17'
          cache: 'npm'
          cache-dependency-path: deploy/package-lock.json

      - name: Install dependencies
        working-directory: deploy
        run: npm install

      - name: Run deploy
        working-directory: deploy
        run: npm start
        env:
          FTP_HOST: ${{ secrets.FTP_HOST }}
          FTP_USER: ${{ secrets.FTP_USER }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
